version: '2'
services:
    uaa-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/uaa/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=uaa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
